### ISSUE TITLE
Questions about vjson

### ISSUE THREAD

**Issue by chmike** [miladibra10/vjson#28]
I’m looking for a package to validate JSON and have a few questions before I start trying your package.

- Will it detect non ASCII characters in the JSON data ? 
- Will it detect unmatched [] or {} ?
- Will it detect missing or exceeding commas ? 
- Will it report the line number and character position in the line of the error ? 
- Are error human readable and more helpful than the errors provided by the standard library ?

**Comment by miladibra10** [comment]
Dear @chmike 
The answers to your questions are:

- **detecting non-ASCII characters**: non-ASCII characters are valid in a JSON file. so the library will not return an error for non-ASCII characters.
- **unmatched `[]` or `{}`**: you can declare required fields (like lists and objects) in your schema. if the input JSON does not have those fields, `vjson` will return an error validating the input JSON.
- **missing or exceeding commas**: Yes, it can detect these problems.
- **reporting line number and character position**: unfortunately `vjson` can not report these stats right now. it could be a good feature for the next updates.
- **human-readable errors**: I tried to return human-readable errors as much as possible in this library.
