### ISSUE TITLE
Allow for marshalling schema to JSON for storage

### ISSUE THREAD

**Issue by brocococonut** [miladibra10/vjson#31]
Having the ability to convert a properly formatted JSON string into a schema is great. But it'd work better if the reverse were also possible. Currently if you try to run a schema through `json.Marshal`, you get something similar to this:

```go
schema := vjson.NewSchema(
	vjson.Float("i").Required(),
	vjson.Array("children", vjson.String("item")),
)

byteStr, _ := json.Marshal(schema)

println(string(byteStr)) // Output: [{},{}]
```

Having complimentary functions to `vjson.ReadFromBytes()`, `vjson.ReadFromString()`, `vjson.ReadFromFile()` such as `schema.WriteToString(...)`, `schema.WriteToBytes(...)`, and `schema.WriteToFile(...)` would enable the proper backing up and restoring of these schemas.

**Comment by miladibra10** [comment]
I will review the PR ASAP.

**Comment by miladibra10** [comment]
Dear @brocococonut 
Your requested feature is implemented. you can use `json.Marshal` method in the standard library in order to create a backup of your schema.
